let tabuada5 = (5*1)
console.log(tabuada5)
tabuada5 = (5*2)
console.log(tabuada5)
tabuada5 = (5*3)
console.log(tabuada5)
tabuada5 = (5*4)
console.log(tabuada5)
tabuada5 = (5*5)
console.log(tabuada5)
tabuada5 = (5*6)
console.log(tabuada5)
tabuada5 = (5*7)
console.log(tabuada5)
tabuada5 = (5*8)
console.log(tabuada5)
tabuada5 = (5*9)
console.log(tabuada5)
tabuada5 = (5*10)
console.log(tabuada5)